# Generated by Django 3.0.5 on 2020-09-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200929_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='작업이름'),
        ),
    ]
