# Generated by Django 3.0.5 on 2020-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200929_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
